modLoader="javafml"
loaderVersion="[40,)"
license="PINEAPPLE"
[[mods]]
modId="thursday_delight"
version="${file.jarVersion}"
displayName="With Thursday Delight"
logoFile="thursday_delight.png"
credits="Someoneice"
authors="Someoneice"
description='''
'''
[[dependencies.thursday_delight]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.thursday_delight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
